"""Add ImportMapping and complaint fields to Order

Revision ID: 1e17f3befee1
Revises: af9df96d08da
Create Date: 2026-10-04 15:58:21.359345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e17f3befee1'
down_revision = 'af9df96d08da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('complaint_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('complaint_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('complaint_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('external_id', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_orders_external_id'), ['external_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_external_id'))
        batch_op.drop_column('external_id')
        batch_op.drop_column('complaint_date')
        batch_op.drop_column('complaint_status')
        batch_op.drop_column('complaint_text')

    # ### end Alembic commands ###
